### ISSUE TITLE
Reset gamma with oneshot mode.

### ISSUE THREAD

**Issue by michael-n0813** [spantaleev/redshift-scheduler#5]
https://github.com/spantaleev/redshift-scheduler/blob/0ae283c3319e93e1a50984c1fd4f866f788034f3/src/temperature_setters.vala#L14

Needs "redshift -P -O"
('-P' resets gamma ramps before applying new temp)

As changed in redshift v1.12

https://github.com/jonls/redshift/issues/618

**Comment by spantaleev** [comment]
I've also noticed this problem a day or two ago.
Happy to see that by the time I got to investigating it, you had already reported the actual root cause. :bowing_man: :+1: 

I've patched things up. For newer versions (`redshift >= 1.12`), we add the `-P` flag.
For older versions, we retain the old behavior (no `-P` flag).

`v1.2.0` of `redshift-scheduler`  is released, which includes the fixes.
