### ISSUE TITLE
Update README to indicate that redshift now includes the features which redshift-scheduler was designed for

### ISSUE THREAD

**Issue by maximumpeaches** [spantaleev/redshift-scheduler#7]
At this point in time it's easy to configure redshift to run at specific times, and to shift colors gradually. It would be nice to update the README.md on this project to indicate that redshift does these things. Might save people some confusion when they're reading this project's README, and would be quick to do.

**Comment by spantaleev** [comment]
How?

I still don't think users are in control over what temperature values `redshift` picks. Those are still magically determined by sunrise/sunset times alone, right?

--------

it does seem like `redshift` now has an `-r` flag:

> -r            Disable fading between color temperatures

Not sure if this existed before. Perhaps not. Maybe it does work well and provides a gradual transition around sunset/sunrise times, making `redshift-scheduler` less necessary.

Our README says:

> redshift's temperature transitions are somewhat fast (strikingly visible and thus, annoying)

So I think that this flag may have existed previously as well. `redshift` may have been doing things gradually, but still "somewhat fast" *according to me* (which is, of course, subjective). I don't think the README is *that* inaccurate (if at all).

Even if redshift transitions the temperature very gradually now, `redshift-scheduler` still provides useful functionality, I think. redshift-scheduler still provides the unique feature of adjusting color temperature according to your own schedule (and with your own as-gradually-as-you-want or as-abruptly-as-you-want transitions), regardless of sunrise/sunset times.

**Comment by maximumpeaches** [comment]
You have to modify the redshift.conf file [as seen here](https://github.com/jonls/redshift/blob/master/redshift.conf.sample#L20-L25).

**Comment by spantaleev** [comment]
Looks like I forgot to respond here.

My attention was brought to this old issue because someone has reported the [redshift-scheduler AUR package](https://aur.archlinux.org/packages/redshift-scheduler) as unmaintained and "unnecessary" (because redshft supposedly has the same functionality built in).

This is not true.

Being able to specify `dawn-time` and `dusk-time`  for `redshift` does not make it do what `redshift-scheduler` does. It only lets people manually specify when the sun goes down and up, and then redshift does its magical temperature transitions based on these 2 settings.

`redshift-scheduler` is much more powerful. It lets you specify an infinte number of temperature transitions in its `rules.conf` file (see a [sample configuration here](https://github.com/spantaleev/redshift-scheduler/blob/master/resources/rules.conf.dist)). It's for people who find the "dawn/dusk" situation not powerful enough.

Say you're working at night and are doing important work from 04:00 to 05:00 while it's still dark outside. Regardless of the sun (and of dawn/dusk), redshift-schedulers lets you specify a custom temperature (almost brightest @ 6000K) for that specific period. Say you want to transition to sleeping from 05:00 to 05:30 - redshift-scheduler can gradually decrease the temperature to your desired level (e.g. 3500K) over these 30 minutes. You may have a few other "brighten" or "redshift" intervals (each with different temperature levels) during the day.

redshift-scheduler was developed because **redshift only allows for one daily transition between 2 temperature levels**. Redshift lets people control dawn/dusk time now, but that still doesn't solve the problem of having your screen "redshift" multiple times per day according to your own exact schedule. With redshift-scheduler, you can do as many daily transitions between as many temperature levels as you wish.

**Comment by maximumpeaches** [comment]
Thanks @spantaleev. What do you think about adding some mention of redshift-scheduler to the README.md for redshift? I imagine the users of redshift would also find redshift-scheduler useful.

**Comment by spantaleev** [comment]
It could be done. If you feel like it, please submit a PR there!

Today, I've updated the [Redshift page on the ArchWiki](https://wiki.archlinux.org/title/Redshift) to mention redshift-scheduler briefly. I've also updated the Github topic tags for this repository to potentially make this software more discoverable.
